### ISSUE TITLE
Add support for 少数派 metrics

### ISSUE THREAD

**Issue by hayschan** [spencerwooo/Substats#20]
Currently, there is follower counts support in Substats.  It would be nice if it support metrics such as read counts, word count, etc.
![image](https://user-images.githubusercontent.com/25737801/96330152-94518f80-1085-11eb-8296-d6418e060da8.png)

**Comment by spencerwooo** [comment]
You can easily fetch said metrics from SSPAI's own API without authentication if you want:

```http
GET https://sspai.com/api/v1/user/slug/info/get?slug={user_id}
```

Substats' main purpose is to fetch **the number of fans / followers** and **provide a easy-enough interface to add them up** (hence the feature introduced in [Multiple sources with a single query string](https://substats.spencerwoo.com/query.html#multiple-sources-with-a-single-query-string)). Although there are some exceptions (like the Reddit Karma and Jike highlights...), I don't think I'll be adding these specific metrics from SSPAI to the Substats' API. Thanks for understanding.

**Comment by spencerwooo** [comment]
Another reason why I specifically included Jike's metric and not SSPAI's metrics is that SSPAI's API is simple enough to use directly with Shields.io but Jike's stats require a bit of hacking and definitely requires a third-party proxy service.
