### ISSUE TITLE
没有缓存模块？

### ISSUE THREAD

**Issue by chawyehsu** [spencerwooo/Substats#23]
好像每一次请求都是即时向上游服务发起请求抓取实时数据的？

**Comment by spencerwooo** [comment]
是的... :laughing: Cloudflare Worker本身也没有那种类似存储的东西，除了刚出的那个 KV storage，这个只相当于一个中转 proxy 罢啦

**Comment by chawyehsu** [comment]
怪不得每次都得等“半分钟”😂，source 越多越久。Worker 好像有个 [Cache API](https://developers.cloudflare.com/workers/learning/how-the-cache-works#cache-api)([Example](https://developers.cloudflare.com/workers/examples/cache-api)) 可以短暂缓存 Worker 的数据，可以研究下。

**Comment by chawyehsu** [comment]
我打算尝试实现一下。初步看了下还是有点复杂的，涉及到三层 Cache 的控制：Fetch 层，Edge 层以及 Browser 层。

**Comment by spencerwooo** [comment]
好家伙…
