### ISSUE TITLE
Requests for supporting new platforms / 有关支持新平台的请求

### ISSUE THREAD

**Issue by spencerwooo** [spencerwooo/Substats#3]
## Submitting a request for supporting new platforms

If you want/wish Substats could support a new service/platform/website, please post comments directly under this issue.

如果你希望 Substats 可以支持一个新的平台、服务或网站，请直接在这一 issue 下面进行评论。你可以用「爱发电」来直接助力我对新服务与平台的支持！

[![爱发电](https://img.shields.io/badge/%E7%88%B1%E5%8F%91%E7%94%B5-@SpencerWoo-946ce6?labelColor=24292e)](https://afdian.net/@spencerwoo)

---

If you are willing to/going to directly contribute on supporting new services/platforms/websites, feel free to file a pull request after implementing said features.

如果你希望或准备直接提交一个支持新平台、网站或服务的功能，请直接向本项目进行 Pull Request，我们欢迎各种帮助。

---

Contribution guidelines are available here: [How to contribute - Substats Docs](https://substats.spencerwoo.com/dev/)

环境搭建与贡献指南的参考位于：[How to contribute - Substats Docs](https://substats.spencerwoo.com/dev/)

## Platforms Milestone

_(Future updates will all be posted here.)_

### Upcoming

- [ ] **CSDN** (no obvious API)
- [ ] **SegmentFault** (no obvious API)

### Newly supported _(Incomplete list)_

- [x] 即刻（大 J 终于归来~）
- [x] Unsplash (Credits to @yiukuenchu)
- [x] 爱发电充电人次
- [x] 爱发电月收入

**Comment by liziyi0914** [comment]
Bilibili播放量 点赞数 投币数 收藏数

**Comment by MiracleXYZ** [comment]
YouTube
尽管只能显示缩略的数据（123456→123000），但有总比没有好……

**Comment by spencerwooo** [comment]
> YouTube
> 尽管只能显示缩略的数据（123456→123000），但有总比没有好……

@zwithz 快，有人催 YouTube 啦！

**Comment by zwithz** [comment]
> > YouTube
> 
> > 尽管只能显示缩略的数据（123456→123000），但有总比没有好……
> 
> 
> 
> @zwithz 快，有人催 YouTube 啦！

哈哈哈哈哈哈，我看看要怎么弄，Youtube要认证🤣

**Comment by zwithz** [comment]
> > Bilibili播放量 点赞数 投币数 收藏数
> 
> 
> 
> @liziyi0914 **目前不准备处理除了粉丝数量以外的数据**。另外 API 设计之初是希望能够将多个平台粉丝数量、订阅数量等加起来进行汇总，因此 **设计了多个请求的串联**。如果处理 B 站视频这四个数据的话，没办法将四个值跟其他 API 路由结合。
> 
> 
> 
> 另外如果你想显示 B 站的视频信息，可以直接用 B 站自己的公开可访问的 API 啊。比如这个：
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/32114380/77551518-6cce8600-6eed-11ea-937d-18a8c4dc027b.png)
> 
> 

B站API只提供了用户的粉丝数，单个视频的播放量、投币数量、收藏等。暂无总播放量之类的的API，可以考虑爬用户空间上显示的`总播放量`、`获赞数`。

**Comment by spencerwooo** [comment]
这个 issue 关了，不太方便回溯或者看最新的。一个 issue 一个 issue 来提好了 (●'◡'●)
