### ISSUE TITLE
CoolApk 无法识别粉丝数量

### ISSUE THREAD

**Issue by TheMelody** [spencerwooo/substats#48]
链接如下：

https://api.spencerwoo.com/substats/?source=coolapk&queryKey=2904535

**Comment by spencerwooo** [comment]
确实，酷安的应用内 API 调用方式很久没更新了，很可能当前 substats 使用的方法在新版本的酷安 App 里已经 deprecated 了，但是目前我这边没找到更新的调用方法，暂时没办法解决。另外现在 API 路由是

```
https://api.swo.moe/stats/coolapk/466253
```

**Comment by TheMelody** [comment]
> 
期待修复，另外，能增加：[稀土掘金](https://juejin.cn/)的粉丝关注的数量吗？
