### ISSUE TITLE
index.js totalSubs 改为''比较好吧

### ISSUE THREAD

**Issue by bboysoulcn** [spencerwooo/Substats#5]
```javascript
async function fetchStats(sources, queryKey) {
  // function's returning value
  const fetchStatsRes = {
    totalSubs: '',
    subsInEachSource: {},
    failedSources: {},
  }
```

**Comment by spencerwooo** [comment]
有理由吗？

**Comment by spencerwooo** [comment]
@bboysoulcn 我来解释一下吧，这个 `totalSubs` 是初始化一个请求里总订阅人数（总粉丝数）的，所以下面你可以看到 `fetchStatsRes.totalSubs += res.value.subs`，这个接口返回的都是数字，所以 `totalSubs` 初始化为 0。

**Comment by bboysoulcn** [comment]
> @bboysoulcn 我来解释一下吧，这个 `totalSubs` 是初始化一个请求里总订阅人数（总粉丝数）的，所以下面你可以看到 `fetchStatsRes.totalSubs += res.value.subs`，这个接口返回的都是数字，所以 `totalSubs` 初始化为 0。

嗯嗯，只是我觉得字符型通用性比较好，如果返回值是一个字符串会变成。 0字符串。这样子

**Comment by spencerwooo** [comment]
> > @bboysoulcn 我来解释一下吧，这个 `totalSubs` 是初始化一个请求里总订阅人数（总粉丝数）的，所以下面你可以看到 `fetchStatsRes.totalSubs += res.value.subs`，这个接口返回的都是数字，所以 `totalSubs` 初始化为 0。
> 
> 嗯嗯，只是我觉得字符型通用性比较好，如果返回值是一个字符串会变成。 0字符串。这样子

@bboysoulcn 懂了，你说的这个字符串拼接的问题会在各个 handler 里处理，不会让它返回成字符串的。（至少我还没发现返回成别的的情况）

**Comment by bboysoulcn** [comment]
> @bboysoulcn 懂了，你说的这个字符串拼接的问题会在各个 handler 里处理，不会让它返回成字符串的。（至少我还没发现返回成别的的情况）

嗯嗯

**Comment by bboysoulcn** [comment]
> > > @bboysoulcn 我来解释一下吧，这个 `totalSubs` 是初始化一个请求里总订阅人数（总粉丝数）的，所以下面你可以看到 `fetchStatsRes.totalSubs += res.value.subs`，这个接口返回的都是数字，所以 `totalSubs` 初始化为 0。
> > 
> > 
> > 嗯嗯，只是我觉得字符型通用性比较好，如果返回值是一个字符串会变成。 0字符串。这样子
> 
> @bboysoulcn 懂了，你说的这个字符串拼接的问题会在各个 handler 里处理，不会让它返回成字符串的。（至少我还没发现返回成别的的情况）

我写了一个返回用户ip的，但是因为是cloudflare去请求的接口，所以不能找到实际的ip，所以就发现了这个问题

https://img.shields.io/badge/dynamic/json?color=red&label=ip&query=%24.data.totalSubs&url=http%3A%2F%2Fsb.bboysoul.cn%2Fsubstats%2F%3Fsource%3Dip%26queryKey%3Dip

**Comment by bboysoulcn** [comment]
http://sb.bboysoul.cn/substats/?source=ip&queryKey=ip

**Comment by spencerwooo** [comment]
> http://sb.bboysoul.cn/substats/?source=ip&queryKey=ip

你做这种 badge 的话可以不用拿 Cloudflare 转啊，直接告诉 Shields.io 请求 IP 的 API 不就好了嘛！

**Comment by bboysoulcn** [comment]
> > http://sb.bboysoul.cn/substats/?source=ip&queryKey=ip
> 
> 
> 
> 你做这种 badge 的话可以不用拿 Cloudflare 转啊，直接告诉 Shields.io 请求 IP 的 API 不就好了嘛！

对的，我就练下手，没有写过前端，无聊玩玩

**Comment by spencerwooo** [comment]
@bboysoulcn 添加了对 API 字符串数据返回的支持，详见 `afdian.js` 里面 `afdianIncome` 的实现，以及 `index.js` 里面特殊 API 的声明。
