### ISSUE TITLE
Zhihu API broken - 知乎API坏掉了

### ISSUE THREAD

**Issue by liyucheng09** [spencerwooo/substats#58]
Zhihu badge broken due to the api stop working. See below.

![image](https://github.com/spencerwooo/substats/assets/27999909/1a90528e-cf3b-4042-8b3f-2c637411f4c3)

Reason of error: api broken
`https://api.swo.moe/stats/zhihu/li-yu-cheng-15`
throws:
`{"source":"zhihu","key":"li-yu-cheng-15","failed":true,"message":"请求参数异常，请升级客户端后重试。"}`

**Comment by liyucheng09** [comment]
`https://www.zhihu.com/api/v4/members/${key}?include=follower_count`

其实是知乎的这个接口挂了，暂时没有解决办法。

**Comment by hxhcreate** [comment]
同有此问题，感谢帮助
