### ISSUE TITLE
这个效果是哪里找的

### ISSUE THREAD

**Issue by Qzhangqi** [spencerwooo/Substats#6]
https://api.spencerwoo.com/substats/  这个页面的代码框效果 太好看了

**Comment by spencerwooo** [comment]
您好，是我自己写的，参考的：[Animate a Container on Mouse Over Using Perspective and Transform](https://css-tricks.com/animate-a-container-on-mouse-over-using-perspective-and-transform/)，但是具体代码有很大改动，比如阴影效果就是另外的实现。两个关键文件开源在仓库的 [`styles`](https://github.com/spencerwooo/Substats/tree/master/styles) 文件夹下，可以自己看一下。
