### ISSUE TITLE
Badge maker

### ISSUE THREAD

**Issue by kidonng** [spencerwooo/Substats#9]
It will be useful (and cool😎) if we can have a badge maker like [Shields.io](https://shields.io/).

I made a demo: https://swiss.vercel.app/substats-badge-creator

**Comment by spencerwooo** [comment]
一直有此意，你可以看 VuePress 里面我还单独留了一个页面（[Substats/docs/builder/](https://github.com/spencerwooo/Substats/tree/master/docs/builder)），但一直没时间搞……等我有空再来实现

**Comment by kidonng** [comment]
我把 Demo 扩展完整了，如果您不介意的话可以在文档中放一个链接方便大家使用。

![image](https://user-images.githubusercontent.com/44045911/85988959-68e95d00-ba22-11ea-92b9-51e882a5b4a5.png)

**Comment by spencerwooo** [comment]
谢谢！你是 Vue 写的话直接集成到 VuePress 里面还挺方便的，我这几天写一下吧。我先把导航栏的 Builder 链到你那里 (　o=^•ェ•)o
